apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users-api.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "users-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "users-api.name" . }}
    spec:
      serviceAccountName: {{ include "users-api.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
