apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      serviceAccountName: users-api
      containers:
        - name: users-api
          image: "arnoldsiller/users-api:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
