apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-api-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Siller-Arnold/lab11
    targetRevision: HEAD
    path: helm/users-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
