apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: user-api-namespace
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL09sZW5hOm15c2VjcmV0QHBvc3RncmVzOjU0MzIvcHJvamVjdGRhdGE=  # Base64 codiert
