apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  namespace: user-api-namespace
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: users-api:latest
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args:
            - alembic upgrade head
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
      restartPolicy: Never
