# This file contains the Kubernetes secret for database credentials.
# The secret is used to store sensitive information such as database username, password, and host.
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: user-api-namespace
type: Opaque
stringData:
  POSTGRES_USER: Olena
  POSTGRES_PASSWORD: mysecret
  POSTGRES_DB: projectdata
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
