apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: user-api-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "Olena"
            - name: POSTGRES_PASSWORD
              value: "mysecret"
            - name: POSTGRES_DB
              value: "projectdata"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: user-api-namespace
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
