# This file defines a PersistentVolume (PV) for PostgreSQL in a Kubernetes cluster.
# The PV is used to store PostgreSQL data and is backed by local storage.
# The PV is created in the "user-api-namespace" namespace and has a capacity of 1Gi.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: user-api-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/tmp/k8s-postgres-data"
