apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: user-api-namespace
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
