apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: user-api-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api-container
          image: users-api:latest
          imagePullPolicy: Never  # Bild lokal verwenden, ohne aus einer Registry zu ziehen
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
          command: ["/bin/sh"]
          args: ["-c", "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"]
      restartPolicy: Always
